version: '3.8'

services:
  # API 서버 (운영용)
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.prod
    container_name: ontology-chat-api-prod
    ports:
      - "8000:8000"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      # Neo4j 설정 (외부 서비스)
      - NEO4J_URI=${NEO4J_URI:-neo4j://192.168.0.10:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      # OpenSearch 설정 (외부 서비스)
      - OPENSEARCH_URL=${OPENSEARCH_HOST:-http://192.168.0.10:9200}
      - OPENSEARCH_USER=${OPENSEARCH_USER:-admin}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
      # OpenAI 설정
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Langfuse 트레이싱 설정
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      # 로깅 설정
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - OLLAMA_HOST=${OLLAMA_HOST:-http://192.168.0.11:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-qwen3:8b-q8_0}
    networks:
      - ontology-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # UI 서버 (운영용)
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui.prod
    container_name: ontology-chat-ui-prod
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    depends_on:
      - api
    networks:
      - ontology-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: ontology-chat-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - ui
    networks:
      - ontology-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3


  # 모니터링 - Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: ontology-chat-prometheus-prod
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data_prod:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - ontology-network
    restart: unless-stopped

  # 모니터링 - Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: ontology-chat-grafana-prod
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data_prod:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - ontology-network
    restart: unless-stopped

volumes:
  prometheus_data_prod:
  grafana_data_prod:

networks:
  ontology-network:
    driver: bridge
