version: '3.8'

services:
  # API 서버
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ontology-chat-api
    ports:
      - "8000:8000"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - PYTHONPATH=/app
      # Neo4j 설정
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      # OpenSearch 설정
      - OPENSEARCH_URL=http://opensearch:9200
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASSWORD=admin
      # OpenAI 설정
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    depends_on:
      - neo4j
      - opensearch
    networks:
      - ontology-network
    volumes:
      - ./api:/app/api
    restart: unless-stopped

  # UI 서버
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: ontology-chat-ui
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
      - PYTHONPATH=/app
    depends_on:
      - api
    networks:
      - ontology-network
    volumes:
      - ./ui:/app/ui
    restart: unless-stopped

  # Neo4j 데이터베이스
  neo4j:
    image: neo4j:5.15-community
    container_name: ontology-chat-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - ontology-network
    restart: unless-stopped

  # OpenSearch
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: ontology-chat-opensearch
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - ontology-network
    restart: unless-stopped

  # OpenSearch Dashboards (선택사항)
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: ontology-chat-opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch
    networks:
      - ontology-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  opensearch_data:

networks:
  ontology-network:
    driver: bridge
